FROM ros:melodic-ros-core-bionic

RUN apt update &&\
    apt install -y python-rosdep build-essential git python-pip python3-pip python-virtualenv python-rospkg ros-melodic-rosmon &&\
    sudo rosdep init && rosdep update &&\
    pip3 install pandas &&\
    pip3 install behave &&\
    sudo apt-get install python3-rosdep python3-rosinstall-generator python3-vcstool &&\
    sudo apt-get install python3-pybind11 &&\
    sudo apt-get install python-pybind11


ENV DISPLAY=:0
ENV QT_X11_NO_MITSHM=1

COPY .devcontainer/additional_bashrc.sh /root/.additional_bashrc

RUN cat "/root/.additional_bashrc" >> /root/.bashrc && rm /root/.additional_bashrc



